name: Unittests

on: [pull_request]

jobs:
  unittest:
    runs-on: ubuntu-latest
    env:
      DATABASE: "sqlite:///./test.db"
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest coverage python-dateutil
        pip install -r requirements.txt
    - name: Analysing the code with pytest and coverage
      run: |
        coverage run -m pytest
        coverage report --fail-under=100
